version: '3.8'

services:
  frontend:
    image: def1s/unishare-frontend:latest
    ports:
      - "3000:80"
    networks:
      - app-network
    restart: always

  backend:
    image: def1s/unishare-backend:latest
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/nest
      CLIENT_URL: http://176.114.90.241
    #      CLIENT_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db  # Сохраняем данные в volume
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
